indentation fix

diff --git a/.github/workflows/register-commands-staging.yaml b/.github/workflows/register-commands-staging.yaml
--- a/.github/workflows/register-commands-staging.yaml
+++ b/.github/workflows/register-commands-staging.yaml
@@ -8,8 +8,8 @@ jobs:
     environment: staging
     steps:
        - name: Fail if required env variable is missing
-       if: $ {{!secrets.DISCORD_TOKEN}}
-       run: echo "Requires env variables is missing!" && exit 1
+        if: $ {{!secrets.DISCORD_TOKEN}}
+        run: echo "Requires env variables is missing!" && exit 1
   Register-Commands:
     runs-on: ubuntu-latest
     environment: staging
